name: Bug Report
description: Report a bug or error in the specifications
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a bug report. Below, you will find a few questions to help you give us the information needed to handle the report.
  - type: input
    id: location
    attributes:
      label: Location (url) of the error
      description: Please enter the url of the published page containing the bug or error
      placeholder: ex. https://docs.govstack.global/contribution
    validations:
      required: true
  - type: textarea
    id: what-bug
    attributes:
      label: What is the bug or error?
      description: What do you consider to be incorrect and why is is incorrect?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.9.0RC1 
        - development
    validations:
      required: true
  - type: checkboxes
    id: final-questions
    attributes:
      label: Final questions
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://govstack.global/coc)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have checked the [list of issues](https://github.com/GovStackWorkingGroup/specifications/issues) and confirm this bug has not already been reported
          required: true

